// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/28/2024, 6:29:28 PM
const configMerger = require("/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/plugins/**/*.{js,ts,mjs}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/config/**/*.{js,ts,mjs}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/composables/**/*.{js,ts,mjs}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/utils/**/*.{js,ts,mjs}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hyegyeonglee/Desktop/dev/gyeong-sArtprofile/app.config.{js,ts,mjs}"] }));

module.exports = config
